# Generated by Django 4.2.5 on 2024-03-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_entrenador_equipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=60)),
                ('email_contacto', models.EmailField(max_length=254)),
                ('nombre_agencia', models.CharField(max_length=60)),
            ],
        ),
    ]
