# Generated by Django 4.2.5 on 2024-03-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_representante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Representante',
        ),
    ]
