# Generated by Django 4.2.5 on 2024-03-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('agencia', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
